# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teamsize',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
